# Supprimez l'instruction `version: '3.1'` si vous utilisez Docker Compose V2
version: '3.1'

services:

  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3305:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  db_data:
    driver: local
